<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="color-scheme" content="light dark">
    <script>
        (() => {
            let preference;
            try { preference = localStorage.getItem('frangolinos-theme'); } catch {}
            document.documentElement.dataset.theme = preference === 'dark' || preference === 'light' ? preference : (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
        })();
    </script>
    <title>Frangolinos · O nosso racha</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <aside class="sidebar">
        <a class="brand" href="{{ route('home') }}"><span class="brand-icon">✳</span><span>frangolinos<small>FUTEBOL ENTRE AMIGOS</small></span></a>
        <div class="nav-label">NOSSO RACHA</div>
        <nav aria-label="Navegação principal">
            <button class="nav-item active" data-tab="profile"><span>☺</span> Meu perfil</button>
            <button class="nav-item" data-tab="match"><span>◉</span> Central da partida</button>
            <button class="nav-item" data-tab="days"><span>▦</span> Dias de racha</button>
            <button class="nav-item" data-tab="players"><span>♧</span> Jogadores <b id="nav-count">0</b></button>
            <button class="nav-item" data-tab="statistics"><span>▥</span> Estatísticas</button>
            <button class="nav-item" data-tab="ranking"><span>♜</span> Artilharia</button>
            <button class="nav-item" data-tab="history"><span>◷</span> Histórico</button>
        </nav>
        <div class="sidebar-bottom"><div class="club-icon">F</div><div>Racha dos amigos<small>A resenha começa em campo.</small></div></div>
    </aside>
    <main>
        <header class="topbar"><span>O nosso racha. A nossa história.</span><div class="topbar-actions"><span id="today"></span><button type="button" id="theme-toggle" class="theme-toggle" aria-label="Ativar modo escuro" aria-pressed="false"><span id="theme-icon" aria-hidden="true">☾</span><span id="theme-label">Modo escuro</span></button></div></header>
        <div class="content">
            <div class="page-heading"><div><div class="eyebrow">BORA PRO JOGO</div><h1 id="page-title">Meu perfil</h1><p id="page-subtitle">Sua presença e seus números, em um só lugar.</p></div><button class="primary" id="new-match" hidden>＋ Nova partida</button></div>
            <div id="notice" class="notice-toast" hidden><span class="notice-icon" aria-hidden="true">i</span><div class="notice-body"><strong>Frangolinos</strong><span id="notice-message" role="status" aria-live="polite" aria-atomic="true"></span></div><button type="button" id="dismiss-notice" class="notice-close" aria-label="Fechar notificação">×</button></div>
            <section id="tab-profile" class="tab">
                <article class="panel"><div class="panel-heading"><h2 id="profile-title">Quem é você?</h2><button class="secondary" id="share-profile">Copiar link do racha</button></div><p class="muted">O mesmo link para toda a turma. Escolha seu nome; este celular lembra seu perfil. Sem senha ou conta.</p><form id="profile-form" class="inline-form"><label class="sr-only" for="profile-player">Seu nome</label><select id="profile-player" required></select><button class="primary" id="choose-profile">Usar este perfil</button></form><details class="profile-registration"><summary>Meu nome não está na lista</summary><form id="profile-registration-form" class="inline-form"><label class="sr-only" for="profile-name">Nome ou apelido</label><input id="profile-name" placeholder="Seu nome ou apelido" maxlength="60" required><label class="sr-only" for="profile-position">Preferência de posição</label><select id="profile-position"><option value="outfield">Prefiro jogar na linha</option><option value="goalkeeper">Prefiro jogar no gol</option><option value="both">Linha e goleiro</option></select><button class="primary" id="register-profile">Adicionar meu nome e entrar</button></form></details><input id="profile-share-url" readonly aria-label="Link geral do racha" hidden></article>
                <div id="profile-content" hidden><article class="panel" id="profile-attendance-panel"><div class="panel-heading"><h2>Rachas e minha participação</h2></div><div id="profile-notifications"></div><div id="profile-days"></div></article><div id="profile-stats" class="stats-grid"></div><article class="panel"><div class="panel-heading"><h2>Minhas últimas partidas</h2></div><div id="profile-matches"></div></article></div>
            </section>
            <section id="tab-match" class="tab" hidden><div class="day-banner"><div><strong id="active-day-title">Escolha o dia do racha</strong><p id="active-day-info">Confirme as presenças antes de sortear os times.</p></div><div class="day-banner-actions"><button class="secondary" data-tab="days">Ver inscrições →</button></div></div>
                <article class="panel" id="day-session" hidden><div class="panel-heading"><h2>Sessão do dia</h2><span class="tag" id="session-arrival-count"></span></div><p class="muted">Marque quem já chegou ao local. Apenas os presentes entram no sorteio; os demais podem ser adicionados conforme chegarem.</p><div id="day-arrivals" class="arrival-grid"></div><div class="day-controls"><button type="button" class="primary" id="draw-day">Sortear times e preparar partida</button><button type="button" class="secondary" id="finish-day-central">Encerrar dia de racha</button></div></article>
                <div class="stats-grid"><article class="stat"><span>Jogadores do dia <i>♧</i></span><strong id="stat-players">0</strong><small>Presenças confirmadas neste dia</small></article><article class="stat"><span>Partidas finalizadas <i>⚑</i></span><strong id="stat-matches">0</strong><small>Finalizadas neste dia</small></article><article class="stat"><span>Gols marcados <i>◎</i></span><strong id="stat-goals">0</strong><small>Gols do dia, incluindo a partida atual</small></article><article class="stat"><span>Artilheiro do dia <i>♜</i></span><strong class="name-stat" id="stat-leader">—</strong><small id="stat-leader-goals">O primeiro gol pode ser seu</small></article></div>
                <article id="penalties-card" class="panel penalties-card" hidden><h2>Empate · decisão nos pênaltis</h2><p>A partida terminou empatada. Escolha quem venceu a disputa para registrar o resultado e liberar a próxima partida.</p><button class="primary" id="open-penalties">Definir vencedor</button></article>
                <article id="next-match-card" tabindex="-1" class="panel next-match-card" hidden><div class="panel-heading"><h2 id="last-result-title">Próxima partida</h2><span class="tag">VENCEDOR FICA</span></div><p id="rotation-info" class="muted"></p><div id="next-lineup" class="draw-board"></div><div class="day-controls"><button class="primary" id="prepare-next">Preparar próxima partida</button><button class="secondary" data-tab="days">Ver estatísticas do dia</button></div></article>
                <div class="match-layout"><div>
                    <article class="score-card"><div class="score-top"><span class="live-pill" id="match-status">● AGUARDANDO O APITO</span><span id="match-number">PARTIDA DO RACHA</span></div>
                        <div class="scoreboard"><div class="team"><div class="jersey blue">A</div><h2>Time Azul</h2><span id="team-a-count">0 jogadores</span></div><div class="score"><span id="score-a">0</span><em>:</em><span id="score-b">0</span></div><div class="team"><div class="jersey red">B</div><h2>Time Vermelho</h2><span id="team-b-count">0 jogadores</span></div></div>
                        <div class="clock-label" id="clock-label">TEMPO RESTANTE</div><div class="clock" id="clock">10:00</div><div class="clock-caption" id="clock-caption">Monte os times para começar</div>
                        <div class="match-actions"><button class="primary" id="toggle-clock">▶ Iniciar partida</button><button type="button" class="secondary" id="free-match">Partida Livre</button><button class="secondary" id="add-goal">＋ Registrar gol</button><button class="finish" id="finish-match">Finalizar</button></div>
                        <div class="score-footer"><span>◎ Futebol, amizade e uma boa resenha.</span><span id="save-status">Carregando…</span></div>
                    </article>
                    <article class="panel events-panel"><div class="panel-heading"><h2>Lances da partida</h2><span class="muted" id="events-count">0 gols</span></div><div id="events"></div></article>
                </div><div class="right-column"><article class="panel"><div class="panel-heading"><h2>Em campo</h2><span class="tag">OS ESCALADOS</span></div><div id="lineup"></div><div id="vacancies-list"></div><div id="bench-lineup"></div><div id="departed-lineup"></div></article><article class="panel"><div class="panel-heading"><h2>Jogadores presentes</h2><span class="tag" id="present-players-count">0</span></div><div id="present-players"></div></article></div></div>
            </section>
            <section id="tab-days" class="tab" hidden>
                <article class="panel"><div class="panel-heading"><h2>Marcar um dia de racha</h2><span class="tag">A TURMA SE ORGANIZA AQUI</span></div><form id="day-form" class="day-form"><label>Data<input type="date" id="day-date" required></label><label>Início<input type="time" id="day-time" value="19:00" required></label><label>Fim<input type="time" id="day-end-time" value="21:00" required></label><label>Local<input id="day-location" placeholder="Quadra ou campo" maxlength="120" required></label><button class="primary" id="save-day">＋ Marcar racha</button><button type="button" class="secondary" id="cancel-edit-day" hidden>Cancelar alteração</button></form></article>
                <div class="days-layout"><article class="panel"><div class="panel-heading"><h2>Dias marcados</h2></div><div id="days-list"></div></article><article class="panel"><div class="panel-heading"><h2 id="attendance-title">Lista de presença</h2><button class="secondary" id="share-day">Copiar link</button></div><button class="secondary" id="edit-day">Alterar data, horário ou local</button><div id="attendance-details"></div><div id="day-profile-attendance" class="day-controls" hidden><button type="button" class="primary" id="play-day">Jogar</button><button type="button" class="secondary" id="skip-day">Não vou jogar</button></div><form id="attendance-form" class="attendance-form"><label id="attendance-player-label" for="attendance-player">Adicionar jogador cadastrado</label><select id="attendance-player" required></select><div><button class="primary" id="confirm-attendance">Adicionar jogador</button><button type="button" class="secondary" id="cancel-attendance">Não vou</button></div></form><p class="muted">Cada perfil pode confirmar sua participação. Limite: 15 jogadores de linha e 4 goleiros. Goleiros não pagam.</p><div id="payment-summary" class="payment-summary" hidden></div><div id="attendance-list"></div><input id="share-url" readonly aria-label="Link da presença" hidden></article></div>
                <article class="panel day-statistics-panel"><div class="panel-heading"><h2>Estatísticas do dia</h2><span id="day-statistics-status" class="tag">EM ANDAMENTO</span></div><div id="day-statistics"></div></article>
            </section>
            <section id="tab-players" class="tab" hidden><article class="panel"><div class="panel-heading"><h2>A turma do racha</h2><span class="muted">Cadastre os amigos para escalar os times</span></div><form id="player-form" class="inline-form"><label class="sr-only" for="player-name">Nome do jogador</label><input id="player-name" placeholder="Nome ou apelido do jogador" maxlength="60" required><label class="sr-only" for="player-position">Posição</label><select id="player-position"><option value="outfield">Jogador de linha</option><option value="goalkeeper">Goleiro</option><option value="both">Linha e goleiro</option></select><button class="primary">＋ Adicionar jogador</button></form><div class="player-filters"><input id="player-search" type="search" placeholder="Buscar jogador" aria-label="Buscar jogador"><label><input type="checkbox" id="show-archived"> Mostrar arquivados</label></div><div id="players-list"></div></article></section>
            <section id="tab-statistics" class="tab" hidden>
                <div id="general-statistics" class="stats-grid"></div>
                <p class="muted">Estatísticas de todos os rachas e partidas, incluindo a partida em andamento. Quem entrou como substituto também conta como participante. Empates dividem a posição.</p>
                <div class="general-rankings">
                    <article class="panel"><div class="panel-heading"><h2>Mais gols</h2></div><div id="statistics-goals"></div></article>
                    <article class="panel"><div class="panel-heading"><h2>Mais assistências</h2></div><div id="statistics-assists"></div></article>
                    <article class="panel"><div class="panel-heading"><h2>Mais partidas jogadas</h2></div><div id="statistics-games"></div></article>
                </div>
            </section>
            <section id="tab-ranking" class="tab" hidden><article class="panel"><div class="panel-heading"><h2>Quem está com o pé calibrado?</h2><span class="tag">RANKING GERAL</span></div><p class="muted">Gols e participações de todas as partidas, incluindo a partida atual. Empates dividem a posição.</p><div id="ranking-list"></div></article></section>
            <section id="tab-history" class="tab" hidden><article class="panel"><div class="panel-heading"><h2>Jogos que viraram história</h2><span class="tag">PARTIDAS FINALIZADAS</span></div><div id="history-list"></div></article></section>
            <footer class="page-footer"><span>frangolinos <b>·</b> Feito para o nosso futebol.</span><span>Dentro de campo, rivais. Fora dele, amigos.</span></footer>
        </div>
    </main>
    <dialog id="setup-dialog" class="wide-dialog"><form id="setup-form"><div class="dialog-heading"><div><div class="eyebrow">PREPARA A RESENHA</div><h2>Nova partida</h2></div><button type="button" class="icon-button" data-close="setup-dialog" aria-label="Fechar">×</button></div><p class="muted">Apenas os presentes entram no sorteio. São dois times: azul e vermelho. Cada time tem 5 na linha e 1 no gol, com prioridade para os goleiros cadastrados. Os demais ficam no banco.</p><div class="match-rules"><strong>10 minutos · 2 gols para vencer</strong><span>No formato de 10 minutos, o segundo gol encerra a partida. Ao zerar o cronômetro, o alarme toca: finalize quando a bola sair. O formato de 15 minutos não tem limite de gols.</span></div><h3>Quem já chegou?</h3><p class="muted">Marque pelo menos 12 participantes para sortear. Os demais podem ser adicionados ao chegar.</p><div id="setup-arrivals" class="arrival-grid"></div><div id="setup-counts" aria-live="polite"></div><div id="setup-players" class="draw-board"></div><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="secondary" id="balance-teams">⇄ Sortear times</button><button class="primary" id="create-match">Criar partida</button></div></form></dialog>
    <dialog id="edit-player-dialog"><form id="edit-player-form"><div class="dialog-heading"><h2>Editar jogador</h2><button type="button" class="icon-button" data-close="edit-player-dialog" aria-label="Fechar">×</button></div><label class="field-label" for="edit-player-name">Nome ou apelido</label><input id="edit-player-name" maxlength="60" required><label class="field-label" for="edit-player-position">Posição</label><select id="edit-player-position"><option value="outfield">Jogador de linha</option><option value="goalkeeper">Goleiro</option><option value="both">Linha e goleiro</option></select><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button class="primary">Salvar jogador</button></div></form></dialog>
    <dialog id="penalties-dialog"><div class="dialog-heading"><h2>Quem venceu nos pênaltis?</h2><button type="button" class="icon-button" data-close="penalties-dialog" aria-label="Fechar">×</button></div><p class="muted">O placar do jogo fica preservado. As cobranças de desempate não entram na artilharia.</p><div class="penalty-options"><button class="team-winner blue-winner" data-penalty-winner="a">Time Azul venceu</button><button class="team-winner red-winner" data-penalty-winner="b">Time Vermelho venceu</button></div><p class="dialog-notice" role="alert" hidden></p></dialog>
    <dialog id="substitution-dialog"><form id="substitution-form"><div class="dialog-heading"><h2>Substituição ou saída</h2><button type="button" class="icon-button" data-close="substitution-dialog" aria-label="Fechar">×</button></div><label class="field-label" for="outgoing-player">Jogador que sai</label><select id="outgoing-player" required></select><label class="departure-label"><input type="checkbox" id="depart-player" checked> Retirar dos próximos sorteios deste dia</label><label class="field-label" for="incoming-player">Quem entra no lugar?</label><select id="incoming-player"></select><p class="muted">Goleiros têm prioridade para assumir o gol. Sem goleiro disponível, um jogador de linha pode assumir. Goleiros também podem entrar na linha. Os disponíveis são ordenados por quantidade de partidas. Sem substituto, o cronômetro pausa até preencher a vaga.</p><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button class="primary">Confirmar</button></div></form></dialog>
    <dialog id="finish-day-dialog"><div class="dialog-heading"><h2>Encerrar o racha de hoje?</h2><button type="button" class="icon-button" data-close="finish-day-dialog" aria-label="Fechar">×</button></div><p class="muted">Todas as partidas e participações ficam registradas. O resumo final mostra gols, artilheiros, partidas e vitórias por jogador. Uma partida preparada que ainda não começou será descartada.</p><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button class="secondary" data-close="finish-day-dialog">Continuar o racha</button><button class="primary" id="confirm-finish-day">Encerrar dia</button></div></dialog>
    <dialog id="goal-dialog" class="goal-picker-dialog"><form id="goal-form"><div class="dialog-heading"><div><div class="eyebrow">A REDE BALANÇOU</div><h2>Registrar gol</h2></div><button type="button" class="icon-button" data-close="goal-dialog" aria-label="Fechar">×</button></div><p class="goal-picker-intro">Escolha o time e toque no jogador que marcou.</p><div class="goal-team-picker" role="group" aria-label="Time que marcou"><button type="button" class="goal-team-button" id="goal-team-a" data-goal-team="a">● Time Azul</button><button type="button" class="goal-team-button" id="goal-team-b" data-goal-team="b">● Time Vermelho</button></div><input type="hidden" id="goal-player"><input type="hidden" id="goal-assist"><section class="goal-selection-section"><h3><span>1</span> Quem fez o gol?</h3><div id="goal-scorers" class="goal-player-grid"></div></section><section id="goal-assist-section" class="goal-selection-section" hidden><h3><span>2</span> Quem deu o passe? <small>Opcional</small></h3><div id="goal-assist-options" class="goal-player-grid"></div></section><div id="goal-preview" class="goal-preview" aria-live="polite"></div><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="secondary" data-close="goal-dialog">Cancelar</button><button class="primary" id="confirm-goal" disabled>⚽ Registrar gol</button></div></form></dialog>
    <dialog id="confirm-dialog"><div class="dialog-heading"><h2>Fim de jogo?</h2><button class="icon-button" data-close="confirm-dialog" aria-label="Fechar">×</button></div><p class="muted">O placar, os gols e a participação dos jogadores serão registrados no histórico.</p><p class="dialog-notice" role="alert" hidden></p><div class="dialog-actions"><button class="secondary" data-close="confirm-dialog">Continuar partida</button><button class="primary" id="confirm-finish">Finalizar partida</button></div></dialog>
</body>
</html>
